"""AdEcho: collection, validation and evaluation utilities (standard library only)."""
import csv
import hashlib
import io
import json
import math
import statistics
import time
import urllib.request
import urllib.error
from datetime import datetime, timezone
from html import unescape
from html.parser import HTMLParser
from pathlib import Path


def utc_now():
    return datetime.now(timezone.utc).isoformat()


def sha(text):
    return hashlib.sha256(text.encode('utf-8')).hexdigest()


def save_json(path, obj):
    path = Path(path)
    path.parent.mkdir(parents=True, exist_ok=True)
    temp = path.with_suffix(path.suffix + '.tmp')
    temp.write_text(json.dumps(obj, indent=2, ensure_ascii=False), encoding='utf-8')
    temp.replace(path)


class ArticleParser(HTMLParser):
    """Prefer articleBody JSON-LD; otherwise explicit CNA body containers only."""
    def __init__(self):
        super().__init__(convert_charrefs=True)
        self.stack = []
        self.parts = []
        self.json_scripts = []
        self.script = None
        self.title = []
        self.title_depth = 0
        self.body_blocks = 0

    def handle_starttag(self, tag, attrs):
        attrs = dict(attrs)
        classes = set(attrs.get('class', '').split())
        own_body = bool(classes & {'text-long', 'article__content', 'article-body', 'article__body'}) or attrs.get('itemprop') == 'articleBody'
        if own_body:
            self.body_blocks += 1
        inherited_body = self.stack[-1][1] if self.stack else False
        inherited_skip = self.stack[-1][2] if self.stack else False
        skip = inherited_skip or tag in {'script', 'style', 'nav', 'aside', 'figure', 'figcaption', 'button', 'form'}
        if tag == 'script' and attrs.get('type') == 'application/ld+json':
            self.script = []
        if tag == 'h1':
            self.title_depth += 1
        if tag not in {'br', 'img', 'meta', 'link', 'hr', 'input', 'source', 'wbr', 'area', 'base', 'embed', 'param', 'track', 'col'}:
            self.stack.append((tag, own_body or inherited_body, skip))
        if (own_body or inherited_body) and not skip and tag in {'p', 'br', 'h2', 'h3', 'li'}:
            self.parts.append('\n')

    def handle_endtag(self, tag):
        if tag == 'script' and self.script is not None:
            self.json_scripts.append(''.join(self.script))
            self.script = None
        if tag == 'h1':
            self.title_depth = max(0, self.title_depth - 1)
        for i in range(len(self.stack) - 1, -1, -1):
            if self.stack[i][0] == tag:
                if self.stack[i][1] and not self.stack[i][2] and tag in {'p', 'div', 'h2', 'h3', 'li'}:
                    self.parts.append('\n')
                del self.stack[i:]
                break

    def handle_data(self, data):
        if self.script is not None:
            self.script.append(data)
        if self.title_depth:
            self.title.append(data)
        if self.stack and self.stack[-1][1] and not self.stack[-1][2]:
            self.parts.append(data)


def walk_json(obj):
    if isinstance(obj, dict):
        yield obj
        for value in obj.values():
            yield from walk_json(value)
    elif isinstance(obj, list):
        for value in obj:
            yield from walk_json(value)


def clean_body(text):
    # Remove ONLY isolated page labels, never sponsorship phrases inside sentences.
    excluded = {'advertorial', 'brand studio', 'presented by', 'sponsored content',
                'this audio is generated by an ai tool.', 'show more', 'show less'}
    return '\n\n'.join(' '.join(line.split()) for line in unescape(text).splitlines()
                       if line.strip() and ' '.join(line.lower().split()) not in excluded)


def extract_article(html):
    parser = ArticleParser()
    parser.feed(html)
    body = ''
    method = 'explicit_body_container'
    for script in parser.json_scripts:
        try:
            items = list(walk_json(json.loads(script)))
        except ValueError:
            continue
        candidates = [x['articleBody'] for x in items if isinstance(x.get('articleBody'), str)]
        if candidates:
            body = max(candidates, key=len)
            method = 'jsonld_articleBody'
            break
    if not body:
        body = ''.join(parser.parts)
    return clean_body(body), ' '.join(''.join(parser.title).split()), method


def fetch_article(source):
    started = utc_now()
    try:
        req = urllib.request.Request(source['url'], headers={'User-Agent': 'AdEcho-course-project/1.0'})
        with urllib.request.urlopen(req, timeout=25) as response:
            raw = response.read(4000000).decode('utf-8', errors='replace')
        body, title, method = extract_article(raw)
        if len(body.split()) < 60:
            return dict(source, collection_status='needs_manual_text', error='No reliable article body extracted', retrieved_at=started)
        return dict(source, collection_status='collected', text=body, page_title=title,
                    extraction_method=method, retrieved_at=started, text_sha256=sha(body))
    except (urllib.error.URLError, TimeoutError, OSError, ValueError) as exc:
        return dict(source, collection_status='needs_manual_text', error=type(exc).__name__, retrieved_at=started)


def model_input(text):
    # Same limit and exact text for BOTH systems. Declare truncation in the protocol.
    return text.strip()[:20000]


def validate_model_output(obj, text, threshold=0.70):
    if not isinstance(obj, dict):
        raise ValueError('Expected an object')
    if obj.get('label') not in {'native_ad', 'editorial', 'abstain'}:
        raise ValueError('Invalid label')
    conf = obj.get('confidence')
    if type(conf) not in (int, float) or not math.isfinite(conf) or not 0 <= conf <= 1:
        raise ValueError('Invalid confidence')
    cues = obj.get('cues')
    if not isinstance(cues, list) or len(cues) > 3:
        raise ValueError('Invalid cues')
    if not all(isinstance(c, str) and c.strip() and c in text for c in cues):
        raise ValueError('Evidence is not an exact input quote')
    if not isinstance(obj.get('reason'), str) or not obj['reason'].strip():
        raise ValueError('Missing reason')
    out = {k: obj[k] for k in ('label', 'confidence', 'cues', 'reason')}
    out['raw_label'] = out['label']
    out['review_required'] = out['label'] == 'abstain' or conf < threshold or not cues
    if out['review_required']:
        out['label'] = 'abstain'
    return out


def call_model(text, api_key, model, prompt):
    start = time.perf_counter()
    base = {'status': 'input_rejected', 'label': 'abstain', 'api_called': False, 'usage': {}}
    if not isinstance(text, str) or not text.strip():
        return dict(base, reason='Empty input.', latency_seconds=0)
    if len(text) > 20000:
        return dict(base, reason='Input exceeds 20,000 characters.', latency_seconds=0)
    payload = {}
    raw_output = None
    base = {'api_called': True, 'label': None, 'usage': {}}
    try:
        data = {'model': model, 'messages': [{'role': 'system', 'content': prompt},
                {'role': 'user', 'content': json.dumps({'article': text})}],
                'temperature': 0, 'max_tokens': 500, 'response_format': {'type': 'json_object'}}
        req = urllib.request.Request('https://openrouter.ai/api/v1/chat/completions',
            data=json.dumps(data).encode('utf-8'),
            headers={'Authorization': 'Bearer ' + api_key, 'Content-Type': 'application/json'})
        with urllib.request.urlopen(req, timeout=60) as response:
            payload = json.load(response)
        base['usage'] = payload.get('usage') or {}
        base['generation_id'] = payload.get('id')
        base['actual_model'] = payload.get('model')
        raw_output = payload['choices'][0]['message']['content']
        result = validate_model_output(json.loads(raw_output), text)
        base.update(result, status='ok')
    except urllib.error.HTTPError as exc:
        base.update(status='api_error', http_status=exc.code)
    except (urllib.error.URLError, TimeoutError, OSError):
        base.update(status='network_error')
    except (ValueError, TypeError, KeyError, IndexError):
        base.update(status='invalid_response')
    base['raw_output'] = raw_output
    base['latency_seconds'] = round(time.perf_counter() - start, 4)
    return base


def score_rows(rows, method):
    n = len(rows)
    answers = [(r['label'], r[method].get('label')) for r in rows]
    answered = [(a, p) for a, p in answers if p in {'native_ad', 'editorial'}]
    correct = sum(a == p for a, p in answers)
    recalls = [sum(a == k and p == k for a, p in answers) / sum(a == k for a, _ in answers)
               for k in ('native_ad', 'editorial') if any(a == k for a, _ in answers)]
    result = {'n': n, 'correct': correct, 'accuracy_all': correct / n if n else None,
              'balanced_accuracy_all': sum(recalls) / 2 if len(recalls) == 2 else None,
              'coverage': len(answered) / n if n else None,
              'accuracy_answered': sum(a == p for a, p in answered) / len(answered) if answered else None,
              'abstention_rate': sum(p == 'abstain' for _, p in answers) / n if n else None,
              'error_rate': sum(p is None for _, p in answers) / n if n else None}
    result['confusion'] = {k: {p: sum(a == k and q == p for a, q in answers)
                          for p in ['native_ad', 'editorial', 'abstain', None]}
                          for k in ['native_ad', 'editorial']}
    times = [r[method]['latency_seconds'] for r in rows if 'latency_seconds' in r[method]]
    result['mean_latency_seconds'] = statistics.mean(times) if times else None
    if method == 'ai':
        result['L1_valid_response_rate'] = sum(r['ai']['status'] == 'ok' for r in rows) / n if n else None
        costs = [(r['ai'].get('usage') or {}).get('cost') for r in rows if r['ai'].get('api_called')]
        known = [v for v in costs if type(v) in (int, float)]
        result['reported_cost_usd_sum'] = sum(known)
        result['calls_without_cost'] = len(costs) - len(known)
        result['cost_complete'] = bool(costs) and len(known) == len(costs)
        result['cost_per_case_usd'] = sum(known) / n if n and result['cost_complete'] else None
        abstained = [r for r in rows if r['ai'].get('label') == 'abstain']
        raw_binary = [r for r in abstained if r['ai'].get('raw_label') in {'native_ad', 'editorial'}]
        result['abstained_with_raw_binary_decision'] = len(raw_binary)
        result['wrong_raw_decisions_among_those_abstained'] = sum(r['ai']['raw_label'] != r['label'] for r in raw_binary)
    return result
